# Matrices (linear algebra)
Documentation Link: https://docs.sympy.org/latest/modules/matrices/matrices.html

In [1]:
import sympy as sp
sp.init_printing(use_unicode=True)

In [42]:
import numpy as np

## [Creating Matrices](https://docs.sympy.org/latest/modules/matrices/matrices.html#creating-matrices)

In [5]:
mat = sp.Matrix([[1,0,0],[0,0,0]])
display(mat, sp.Matrix([mat, (2,0,-1)]))   # adding row

rowmat = sp.Matrix([[1,2,3]])
colmat = sp.Matrix([1,2,3])
display(rowmat, colmat)

⎡1  0  0⎤
⎢       ⎥
⎣0  0  0⎦

⎡1  0  0 ⎤
⎢        ⎥
⎢0  0  0 ⎥
⎢        ⎥
⎣2  0  -1⎦

[1  2  3]

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

In [7]:
sp.Matrix(3, 2, [1,2,3,4,5,6])

⎡1  2⎤
⎢    ⎥
⎢3  4⎥
⎢    ⎥
⎣5  6⎦

In [11]:
def matfn(i, j):
    if i==j:
        return -2
    elif i==j+1:
        return 1
    elif i+1==j:
        return 1
    else:
        return 0
display(matfn, sp.Matrix(5,5, matfn))

sp.Matrix(3,4, lambda i,j: 1 - (i+j)%2)

<function __main__.matfn(i, j)>

⎡-2  1   0   0   0 ⎤
⎢                  ⎥
⎢1   -2  1   0   0 ⎥
⎢                  ⎥
⎢0   1   -2  1   0 ⎥
⎢                  ⎥
⎢0   0   1   -2  1 ⎥
⎢                  ⎥
⎣0   0   0   1   -2⎦

⎡1  0  1  0⎤
⎢          ⎥
⎢0  1  0  1⎥
⎢          ⎥
⎣1  0  1  0⎦

In [63]:
display('zeros', sp.zeros(2), sp.zeros(2, 3), 'ones', sp.ones(2), sp.ones(2,3),
'diag', sp.diag(1, sp.Matrix([[1,2],[3,4]]), 7), 'eye', sp.eye(4))

'zeros'

⎡0  0⎤
⎢    ⎥
⎣0  0⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

'ones'

⎡1  1⎤
⎢    ⎥
⎣1  1⎦

⎡1  1  1⎤
⎢       ⎥
⎣1  1  1⎦

'diag'

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  2  0⎥
⎢          ⎥
⎢0  3  4  0⎥
⎢          ⎥
⎣0  0  0  7⎦

'eye'

⎡1  0  0  0⎤
⎢          ⎥
⎢0  1  0  0⎥
⎢          ⎥
⎢0  0  1  0⎥
⎢          ⎥
⎣0  0  0  1⎦

## [Basic Manipulation](https://docs.sympy.org/latest/modules/matrices/matrices.html#basic-manipulation)

Indexing and Slicing

In [37]:
M = sp.Matrix(3, 4, [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
display(M, M[4], M[1,2], M[0:2, 1:4], M[3:3,1], M[:,1], M[2,:],
        M[:2,:100], M[:,100:101], sp.Matrix(0,5, [])[:,:])

⎡1  2   3   4 ⎤
⎢             ⎥
⎢5  6   7   8 ⎥
⎢             ⎥
⎣9  10  11  12⎦

⎡2  3  4⎤
⎢       ⎥
⎣6  7  8⎦

[]

⎡2 ⎤
⎢  ⎥
⎢6 ⎥
⎢  ⎥
⎣10⎦

[9  10  11  12]

⎡1  2  3  4⎤
⎢          ⎥
⎣5  6  7  8⎦

[]

[]

In [39]:
M2 = M[:,:]
M2[0,0] = 100
M[0,0] == 100 # unchanged

False

In [51]:
mat = sp.Matrix(np.arange(1,17).reshape(4,4))
display(mat)
mat[2,2] = mat[3,3] = 0
display(mat)
mat[1:,1:] = sp.Matrix(3,3, lambda i,j: 0)
display(mat)

⎡1   2   3   4 ⎤
⎢              ⎥
⎢5   6   7   8 ⎥
⎢              ⎥
⎢9   10  11  12⎥
⎢              ⎥
⎣13  14  15  16⎦

⎡1   2   3   4 ⎤
⎢              ⎥
⎢5   6   7   8 ⎥
⎢              ⎥
⎢9   10  0   12⎥
⎢              ⎥
⎣13  14  15  0 ⎦

⎡1   2  3  4⎤
⎢           ⎥
⎢5   0  0  0⎥
⎢           ⎥
⎢9   0  0  0⎥
⎢           ⎥
⎣13  0  0  0⎦

Arithmetic Operations

In [57]:
M = sp.Matrix(([1,2,3],[4,5,6],[7,8,9]))
M2 = sp.Matrix(3,1,[1,5,0])
display(M - M, M + M, M*M, M*M2, M**2)

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

⎡2   4   6 ⎤
⎢          ⎥
⎢8   10  12⎥
⎢          ⎥
⎣14  16  18⎦

⎡30   36   42 ⎤
⎢             ⎥
⎢66   81   96 ⎥
⎢             ⎥
⎣102  126  150⎦

⎡11⎤
⎢  ⎥
⎢29⎥
⎢  ⎥
⎣47⎦

⎡30   36   42 ⎤
⎢             ⎥
⎢66   81   96 ⎥
⎢             ⎥
⎣102  126  150⎦

Deleting rows and columns using `row_del` and `row_del` respectively

In [58]:
M = sp.Matrix(([1,2,3],[4,5,6],[7,8,9]))
display(M)
M.row_del(0)
display(M)
M.row_del(1)
display(M)

⎡1  2  3⎤
⎢       ⎥
⎢4  5  6⎥
⎢       ⎥
⎣7  8  9⎦

⎡4  5  6⎤
⎢       ⎥
⎣7  8  9⎦

[4  5  6]

Vector operations

In [55]:
v1 = sp.Matrix([1,2,3])
v2 = sp.Matrix([4,5,6])
v3 = v1.cross(v2)
display(v1, v2, v3)

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

⎡4⎤
⎢ ⎥
⎢5⎥
⎢ ⎥
⎣6⎦

⎡-3⎤
⎢  ⎥
⎢6 ⎥
⎢  ⎥
⎣-3⎦

Join Matrices

In [61]:
M1 = sp.ones(3)
M2 = sp.zeros(3,4)
M3 = M1.row_join(M2)
display(M1, M2, M3)
M4 = sp.zeros(4,3)
M1.col_join(M4)

⎡1  1  1⎤
⎢       ⎥
⎢1  1  1⎥
⎢       ⎥
⎣1  1  1⎦

⎡0  0  0  0⎤
⎢          ⎥
⎢0  0  0  0⎥
⎢          ⎥
⎣0  0  0  0⎦

⎡1  1  1  0  0  0  0⎤
⎢                   ⎥
⎢1  1  1  0  0  0  0⎥
⎢                   ⎥
⎣1  1  1  0  0  0  0⎦

⎡1  1  1⎤
⎢       ⎥
⎢1  1  1⎥
⎢       ⎥
⎢1  1  1⎥
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

## [Operations on entries](https://docs.sympy.org/latest/modules/matrices/matrices.html#operations-on-entries)

**`applyfunc`**

In [64]:
matfn1 = lambda x: 5*x
display(sp.eye(3).applyfunc(matfn1))

⎡5  0  0⎤
⎢       ⎥
⎢0  5  0⎥
⎢       ⎥
⎣0  0  5⎦

In [77]:
x, y = sp.symbols('x y')

Mxy = sp.Matrix([[x,y],[1,x*y]])
m = Mxy.inv('ADJ')
display(Mxy, Mxy.inv(), m)
# sp.gcd(tuple())
# not working

⎡x   y ⎤
⎢      ⎥
⎣1  x⋅y⎦

⎡    x           y     ⎤
⎢  ──────    ──────────⎥
⎢   2           2      ⎥
⎢  x  - 1    - x ⋅y + y⎥
⎢                      ⎥
⎢    1          -x     ⎥
⎢──────────  ──────────⎥
⎢   2           2      ⎥
⎣- x ⋅y + y  - x ⋅y + y⎦

⎡  x⋅y       -y    ⎤
⎢────────  ────────⎥
⎢ 2         2      ⎥
⎢x ⋅y - y  x ⋅y - y⎥
⎢                  ⎥
⎢  -1         x    ⎥
⎢────────  ────────⎥
⎢ 2         2      ⎥
⎣x ⋅y - y  x ⋅y - y⎦

In [78]:
m3 = sp.eye(3)*x
display(m3, m3.subs(x,4), m3.subs(x,y))

⎡x  0  0⎤
⎢       ⎥
⎢0  x  0⎥
⎢       ⎥
⎣0  0  x⎦

⎡4  0  0⎤
⎢       ⎥
⎢0  4  0⎥
⎢       ⎥
⎣0  0  4⎦

⎡y  0  0⎤
⎢       ⎥
⎢0  y  0⎥
⎢       ⎥
⎣0  0  y⎦

## [Linear algebra](https://docs.sympy.org/latest/modules/matrices/matrices.html#linear-algebra)

In [93]:
M2 = sp.Matrix(([1, 2, 3], [3, 6, 2], [2, 0, 1]))
display(M2, M2.det(), M2.inv(), # default method is Gaussian Elimination
        M2.inv(method='ADJ'), M2.inv(method='LU'))


⎡1  2  3⎤
⎢       ⎥
⎢3  6  2⎥
⎢       ⎥
⎣2  0  1⎦

⎡-3/14  1/14  1/2 ⎤
⎢                 ⎥
⎢-1/28  5/28  -1/4⎥
⎢                 ⎥
⎣ 3/7   -1/7   0  ⎦

⎡-3/14  1/14  1/2 ⎤
⎢                 ⎥
⎢-1/28  5/28  -1/4⎥
⎢                 ⎥
⎣ 3/7   -1/7   0  ⎦

⎡-3/14  1/14  1/2 ⎤
⎢                 ⎥
⎢-1/28  5/28  -1/4⎥
⎢                 ⎥
⎣ 3/7   -1/7   0  ⎦

In [ ]:
# continue