# NumPy (WsCube Tech)
Video Link: https://youtu.be/-TYSM0CDA4c

Numpy is the fundamental package for scientific computing in python. It's a python library that provides multidimensional array object and various derived objects.

An array is a grid of values and it contains information about the raw data, how to locate an element and how to interpret an element.

Numpy array vs python list:
1. Data types storage.
2. Importing module.
3. Numerical operation.
4. Modification capabilities.
5. Consumption of memory.
6. Speed.

**Importance of numpy:** 
It supplies an enormous libray of high level mathematical functions that operate on these arrays and matrices. Mathematical, logical, shape manipulation, sorting, I/O, discrete Fourier transforms, basic linear algebra, basec statistical operations, random simulation and much more things can be done in numpy.

In [1]:
import numpy as np

In [2]:
list1 = [4,8,3,9,5,0]
ar1 = np.array(list1)
display('list1', list1, type(list1), 'ar1', ar1, type(ar1), ar1.ndim)

'list1'

[4, 8, 3, 9, 5, 0]

list

'ar1'

array([4, 8, 3, 9, 5, 0])

numpy.ndarray

1

In [3]:
ar3 = np.array([[3,8,2,1],[1,4,7,3]])
display('ar3', ar3, ar3.ndim)

'ar3'

array([[3, 8, 2, 1],
       [1, 4, 7, 3]])

2

In [4]:
ar4 = np.array([4.2,7,3,5,0], ndmin=5)
display('ar4', ar4)

'ar4'

array([[[[[4.2, 7. , 3. , 5. , 0. ]]]]])

### Special numpy arrays

In [5]:
arz = np.zeros(5)
display('zeros - Filled with 0\'s', arz)
arz1 = np.zeros((4,2))
display('arz1', arz1)
aro = np.ones(4)
display('ones - Filled with 1\'s', aro)
are = np.empty(4)
display('empty - Empty array', are) # previous memory
arr = np.arange(2, 40, 5)
display('arange - Array with a range of elements', arr)
ard = np.eye(4)
display('eye - Diagonal with 1\'s', ard)
ard1 = np.eye(4,3)
display(ard1)
arl = np.linspace(2, 20, 10)
display('linspace - Values are spaced linearly in a specified interval', arl)

"zeros - Filled with 0's"

array([0., 0., 0., 0., 0.])

'arz1'

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

"ones - Filled with 1's"

array([1., 1., 1., 1.])

'empty - Empty array'

array([1., 1., 1., 1.])

'arange - Array with a range of elements'

array([ 2,  7, 12, 17, 22, 27, 32, 37])

"eye - Diagonal with 1's"

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

'linspace - Values are spaced linearly in a specified interval'

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### Creating numpy arrays with random numbers

In [6]:
arrand = np.random.rand(5)
display('rand - random values between 0 and 1', arrand)
arrand1 = np.random.rand(2,3)
display(arrand1)
arrandn = np.random.randn(6)
display('randn - random values close to 0 (+ or -)', arrandn)
arranf = np.random.ranf(4)
display('ranf - random float values in [0.0, 1.0)', arranf)
arrandi = np.random.randint(5, 15, 5)
display('randint - random integer values in a range', arrandi)

'rand - random values between 0 and 1'

array([0.31186014, 0.33802203, 0.828949  , 0.81360985, 0.62888137])

array([[0.63679552, 0.96859946, 0.95425968],
       [0.31665276, 0.22442158, 0.03475245]])

'randn - random values close to 0 (+ or -)'

array([ 0.96000128,  0.02140321, -0.60684632,  0.24173564,  0.85415802,
       -0.6961203 ])

'ranf - random float values in [0.0, 1.0)'

array([0.92000359, 0.67619109, 0.68991571, 0.28240819])

'randint - random integer values in a range'

array([14,  7, 12, 14, 13])

## Data types of numpy array
1. **`bool_`**: boolean logics (True or False) stored as byte
2. **`int_`**: default integer type (same as C long, normally either int64 or int32)
3. **`Intc`**: identical to C int (normally int32 or int64)
4. **`Intp`**: integer used for indexing (same as C ssize_t, normally either int32 or int64)
5. **`int8`**: byte (-2^7 to 2^7-1)
6. **`int16`**: integer ($-2^{15}$ to $2^{15}-1$)
7. **`int32`**: integer ($-2^{31}$ to $2^{31}-1$)
8. **`int64`**: integer ($-2^{63}$ to $2^{63}-1$)
9. **`unit8`**: unsigned integer (0 to 255)
10. **`unit16`**: unsigned integer (0 to 65535)
11. **`unit32`**: unsigned integer (0 to 4294967295)
12. **`unit64`**: unsigned integer (0 to 184446744073709551615)
13. **`float_`**: shorthand for float64
14. **`float16`**: half precision float: sign bit, 5 bits exponent, 10 bits mantissa
15. **`float32`**: single precision float
16. **`float64`**: double precision float
17. **`complex_`**: shorthand for complex128
18. **`complex64`**: complex number, represented by two 32 bit floats (real and imaginary components)
19. **`complex128`**: complex number, represented by two 64 bit floats (real and imaginary components)

### dtypes as function
1. **`i`** - integer
2. **`b`** - boolean
3. **`u`** - unsigned integer
4. **`f`** - float
5. **`c`** - complex float
6. **`m`** - timedelta
7. **`M`** - datetime
8. **`O`** - object
9. **`S`** - string
10. **`U`** - unicode string
11. **`V`** - the fixed chunk of memory for other types (void)

In [7]:
ar5 = np.arange(10)
display('ar5', ar5, ar5.dtype)
ar6 = np.linspace(0,5,10)
display('ar6', ar6, ar6.dtype)
ar7 = np.array(['a','b','c','d'])
display('ar7', ar7, ar7.dtype)

'ar5'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

dtype('int32')

'ar6'

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

dtype('float64')

'ar7'

array(['a', 'b', 'c', 'd'], dtype='<U1')

dtype('<U1')

In [8]:
list2 = [8,3,5,4,1]
ar8 = np.array(list2)
display('ar8', ar8, ar8.dtype)
ar8a = np.array(list2, dtype = np.int8)
display('ar8a', ar8a, ar8a.dtype)
ar8b = np.array(list2, dtype='f')
display('ar8b', ar8b, ar8b.dtype)
ar8c = np.float16(ar8)
display('ar8c', ar8c, ar8c.dtype)
ar8d = np.complex_(ar8)
display('ar8d', ar8d, ar8d.dtype)
ar8e = ar8.astype(float)
display('ar8e', ar8e, ar8e.dtype)

'ar8'

array([8, 3, 5, 4, 1])

dtype('int32')

'ar8a'

array([8, 3, 5, 4, 1], dtype=int8)

dtype('int8')

'ar8b'

array([8., 3., 5., 4., 1.], dtype=float32)

dtype('float32')

'ar8c'

array([8., 3., 5., 4., 1.], dtype=float16)

dtype('float16')

'ar8d'

array([8.+0.j, 3.+0.j, 5.+0.j, 4.+0.j, 1.+0.j])

dtype('complex128')

'ar8e'

array([8., 3., 5., 4., 1.])

dtype('float64')

## Axes in numpy arrays
For 2d arrays,
1. **`axis=0`**: It goes along one particular column and covers all the rows. (*vertical axis*)
2. **`axis=1`**: It goes along one particular row and covers all the columns. (*horizontal axis*)

For 3d arrays we will get axis=0 (vertical), axis=1 (horizontal) and axis=2 (inside).

## Operations on NumPy Arrays

### `shape`

In [9]:
ar1d = np.array([12,8,3,7.1,5.2])
display('ar1d', ar1d, ar1d.ndim, ar1d.shape)
ar2d = np.array([[7,3,8,1],[0.2,4,3,9]])
display('ar2d', ar2d, ar2d.ndim, ar2d.shape)
ar3d = np.array([[[1,7,3],[1,7,5]],[[3,5,4],[4,0,2]]])
display('ar3d', ar3d, ar3d.ndim, ar3d.shape)
ar8p = np.array(list2, ndmin=3)
display('ar8p', ar8p, ar8p.ndim, ar8p.shape)

'ar1d'

array([12. ,  8. ,  3. ,  7.1,  5.2])

1

(5,)

'ar2d'

array([[7. , 3. , 8. , 1. ],
       [0.2, 4. , 3. , 9. ]])

2

(2, 4)

'ar3d'

array([[[1, 7, 3],
        [1, 7, 5]],

       [[3, 5, 4],
        [4, 0, 2]]])

3

(2, 2, 3)

'ar8p'

array([[[8, 3, 5, 4, 1]]])

3

(1, 1, 5)

### `reshape`

In [10]:
ar9 = np.array(range(2,26,2))
display('ar9', ar9, ar9.shape)
ar9a = ar9.reshape(3,4)
display(ar9a, ar9a.shape)
ar9b = ar9a.reshape(2,2,3)
display(ar9b, ar9b.shape)
ar9one = ar9b.reshape(-1)
display(ar9one)

'ar9'

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

(12,)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

(3, 4)

array([[[ 2,  4,  6],
        [ 8, 10, 12]],

       [[14, 16, 18],
        [20, 22, 24]]])

(2, 2, 3)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

### Arithmetic Operations
1. `np.add(a,b)`: a + b
2. `np.subtract(a,b)`: a - b
3. `np.multiply(a,b)`: a * b
4. `np.divide(a,b)`: a / b
5. `np.mod(a,b)`: a % b
6. `np.power(a,b)`: a**b
7. `np.reciprocal(a)`: 1 / a

In [11]:
a1d = np.array([5,6,7,2,3])
b1d = np.array([1,2,3,5,10])
display('a1d', a1d, 'b1d', b1d)
display('3a-4b+4', 3*a1d -4*b1d +4)
display('a^4 -a^b/b', a1d**4 -a1d**b1d/b1d)
display('a % 2', a1d % 2)

'a1d'

array([5, 6, 7, 2, 3])

'b1d'

array([ 1,  2,  3,  5, 10])

'3a-4b+4'

array([ 15,  14,  13, -10, -27])

'a^4 -a^b/b'

array([  620.        ,  1278.        ,  2286.66666667,     9.6       ,
       -5823.9       ])

'a % 2'

array([1, 0, 1, 0, 1], dtype=int32)

In [12]:
a2d = np.array([[4,3,7,2],[4,2,8,6]])
b2d = np.array([[1,5,3,0],[7,2,6,3]])
display('a2d', a2d, 'b2d', b2d)
display('3a-4b+4', 3*a2d -4*b2d +4)

'a2d'

array([[4, 3, 7, 2],
       [4, 2, 8, 6]])

'b2d'

array([[1, 5, 3, 0],
       [7, 2, 6, 3]])

'3a-4b+4'

array([[ 12,  -7,  13,  10],
       [-12,   2,   4,  10]])

In the operations between 2 arrays, the elements of arrays with same indices are taken into the operations together.

### Arithmetic functions
1. np.min(x)
2. np.max(x)
3. np.argmin(x)
4. np.sqrt(x)
5. np.sin(x)
6. np.cos(x)
7. np.cumsum(x)

In [13]:
display('min(a)', np.min(a2d), 'max(a)', np.max(a2d, axis=0))
display('5sin(a) +4cos(b)', 5*np.sin(a2d) +4*np.cos(b2d))
display('argmin', np.argmin(a2d, axis=0))
display('cumsum', np.cumsum(a1d))

'min(a)'

2

'max(a)'

array([4, 3, 8, 6])

'5sin(a) +4cos(b)'

array([[-1.62280325,  1.84024878, -0.67503699,  8.54648713],
       [-0.76840346,  2.88189979,  8.78747238, -5.35704748]])

'argmin'

array([0, 1, 0, 0], dtype=int64)

'cumsum'

array([ 5, 11, 18, 20, 23], dtype=int32)

## Broadcastening of numpy arrays
The dimension of arrays in operations,
1. should be of same dimension;
2. should be like (1,3) and (3,1) and the output will be like (3,3).

If the conditions are not satisfied in an array operation, we will get **Broadcastening Error**.

In [14]:
display('a1d', a1d, 'b1d', b1d)
display('a1d/b1d', a1d/b1d)
display('ar1', ar1, 'ar8', ar8)
try:
    ar1add8 = ar1 + ar8
except Exception as e:
    print(e)

ar1b = np.array([[1,4,2]])
ar2b = np.array([[1],[4],[7]])
display('ar1b', ar1b, ar1b.shape, 'ar2b', ar2b, ar2b.shape)
ar12b = ar1b +ar2b
display('ar1b +ar2b', ar12b)

'a1d'

array([5, 6, 7, 2, 3])

'b1d'

array([ 1,  2,  3,  5, 10])

'a1d/b1d'

array([5.        , 3.        , 2.33333333, 0.4       , 0.3       ])

'ar1'

array([4, 8, 3, 9, 5, 0])

'ar8'

array([8, 3, 5, 4, 1])

operands could not be broadcast together with shapes (6,) (5,) 


'ar1b'

array([[1, 4, 2]])

(1, 3)

'ar2b'

array([[1],
       [4],
       [7]])

(3, 1)

'ar1b +ar2b'

array([[ 2,  5,  3],
       [ 5,  8,  6],
       [ 8, 11,  9]])

## Indexing and Slicing

### Indexing in arrays
Along an axis, the indices are *[0,1,2,3,4]* or *[-5,-4,-3,-2,-1]*.

In [15]:
display('ar12b', ar12b)
display(ar12b[2,0], ar12b[1])

'ar12b'

array([[ 2,  5,  3],
       [ 5,  8,  6],
       [ 8, 11,  9]])

8

array([5, 8, 6])

### Slicing in arrays
array[**starting index : stopping index : step**]

In [16]:
list3 = [range(5,45,5), range(10,42,4), range(14,30,2), 
         range(2,50,6), np.random.randint(2,10,8)]
ar10 = np.array(list3)
display('ar10', ar10, ar10.shape)
display(ar10[2:10])
display(ar10[1:4, 2::2])
display(ar10[:,-6:-2])

'ar10'

array([[ 5, 10, 15, 20, 25, 30, 35, 40],
       [10, 14, 18, 22, 26, 30, 34, 38],
       [14, 16, 18, 20, 22, 24, 26, 28],
       [ 2,  8, 14, 20, 26, 32, 38, 44],
       [ 4,  9,  7,  4,  5,  2,  8,  2]])

(5, 8)

array([[14, 16, 18, 20, 22, 24, 26, 28],
       [ 2,  8, 14, 20, 26, 32, 38, 44],
       [ 4,  9,  7,  4,  5,  2,  8,  2]])

array([[18, 26, 34],
       [18, 22, 26],
       [14, 26, 38]])

array([[15, 20, 25, 30],
       [18, 22, 26, 30],
       [18, 20, 22, 24],
       [14, 20, 26, 32],
       [ 7,  4,  5,  2]])

## Iterating numpy arrays

In [17]:
display('ar1', ar1)
for elt in ar1:
    print(elt)

'ar1'

array([4, 8, 3, 9, 5, 0])

4
8
3
9
5
0


In [18]:
display('ar12b', ar12b)
for i in ar12b:
    print(i)

for i in ar12b:
    for j in i:
        print(j)

print('np.nditer')
for i in np.nditer(ar12b, flags=['buffered'], op_dtypes=['float']):
    print(i)

print('values with indices : np.ndenumerate')
for ind, val in np.ndenumerate(ar12b):
    print(ind, val)

'ar12b'

array([[ 2,  5,  3],
       [ 5,  8,  6],
       [ 8, 11,  9]])

[2 5 3]
[5 8 6]
[ 8 11  9]
2
5
3
5
8
6
8
11
9
np.nditer
2.0
5.0
3.0
5.0
8.0
6.0
8.0
11.0
9.0
values with indices : np.ndenumerate
(0, 0) 2
(0, 1) 5
(0, 2) 3
(1, 0) 5
(1, 1) 8
(1, 2) 6
(2, 0) 8
(2, 1) 11
(2, 2) 9


## `copy` vs `view` in numpy
1. The copy owns the data but the view doesn't own the data.
2. The copy of an array is a new array and if we change it, the original array will be unchanged. On the other hand view is the original array and if we change it, the original array will also be changed. 

In [19]:
ar1c = ar1.copy()
display('copy ar1c', ar1c)
ar1[0] = 10
ar1c[1] = 11
display('original', ar1, 'copy', ar1c)

'copy ar1c'

array([4, 8, 3, 9, 5, 0])

'original'

array([10,  8,  3,  9,  5,  0])

'copy'

array([ 4, 11,  3,  9,  5,  0])

In [20]:
ar1v = ar1.view()
display('view ar1v', ar1v)
ar1[0] = 20
ar1v[1] = 21
display('original', ar1, 'copy', ar1v)

'view ar1v'

array([10,  8,  3,  9,  5,  0])

'original'

array([20, 21,  3,  9,  5,  0])

'copy'

array([20, 21,  3,  9,  5,  0])

## Join and split

### Join array
Joining means putting contents of 2 or more arrays in a single array.

### `concatenate`

In [21]:
display(a2d, b2d)
ar12bcon = np.concatenate((a2d, b2d), axis=1)
display(ar12bcon)

array([[4, 3, 7, 2],
       [4, 2, 8, 6]])

array([[1, 5, 3, 0],
       [7, 2, 6, 3]])

array([[4, 3, 7, 2, 1, 5, 3, 0],
       [4, 2, 8, 6, 7, 2, 6, 3]])

### `stack`

In [22]:
arst = np.stack((a2d, b2d), axis=0)
display('stack', arst, arst.shape)

arst1 = np.hstack((a2d, b2d))
display('row', arst1, arst1.shape)
arst2 = np.vstack((a2d, b2d))
display('column', arst2, arst2.shape)
arst3 = np.dstack((a2d, b2d))
display('height', arst3, arst3.shape)

'stack'

array([[[4, 3, 7, 2],
        [4, 2, 8, 6]],

       [[1, 5, 3, 0],
        [7, 2, 6, 3]]])

(2, 2, 4)

'row'

array([[4, 3, 7, 2, 1, 5, 3, 0],
       [4, 2, 8, 6, 7, 2, 6, 3]])

(2, 8)

'column'

array([[4, 3, 7, 2],
       [4, 2, 8, 6],
       [1, 5, 3, 0],
       [7, 2, 6, 3]])

(4, 4)

'height'

array([[[4, 1],
        [3, 5],
        [7, 3],
        [2, 0]],

       [[4, 7],
        [2, 2],
        [8, 6],
        [6, 3]]])

(2, 4, 2)

### `split` array
Splitting breaks one array into multiple.

In [23]:
arspl1 = np.array_split(arst1[0], 4)
display('arspl1', arspl1)
arspl1 = np.array_split(arst1, 4, axis=1)
display('arspl1', arspl1)

'arspl1'

[array([4, 3]), array([7, 2]), array([1, 5]), array([3, 0])]

'arspl1'

[array([[4, 3],
        [4, 2]]),
 array([[7, 2],
        [8, 6]]),
 array([[1, 5],
        [7, 2]]),
 array([[3, 0],
        [6, 3]])]

## Numpy arrays functions

### Search array
Searches an array for a certain value and return the indexes that get a match.

In [24]:
display('ar5', ar5)
ar5w = np.where((ar5 % 2) == 0)
display(ar5w)

'ar5'

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

(array([0, 2, 4, 6, 8], dtype=int64),)

### `searchsorted` array
It performs a binary search in the array and returns the index where the specified value would be inserted to maintainthe search order.

In [25]:
ar5ss = np.searchsorted(ar5, [-2,12], side='right')
display(ar5ss)  # try to understand

array([ 0, 10], dtype=int64)

### `sort` array
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [26]:
display(np.sort(ar2d), ar2d)
ar2d.sort()
display(ar2d)
ar13 = np.array(['a','d','b','e','g','p'])
display('ar13', ar13, np.sort(ar13))

array([[1. , 3. , 7. , 8. ],
       [0.2, 3. , 4. , 9. ]])

array([[7. , 3. , 8. , 1. ],
       [0.2, 4. , 3. , 9. ]])

array([[1. , 3. , 7. , 8. ],
       [0.2, 3. , 4. , 9. ]])

'ar13'

array(['a', 'd', 'b', 'e', 'g', 'p'], dtype='<U1')

array(['a', 'b', 'd', 'e', 'g', 'p'], dtype='<U1')

### filter array
Here we can get some elements out of an existing array and crate a new array out of them.

In [27]:
display(ar13)
fltr = [True, False, False, True, False, True]
ar13fl = ar13[fltr]
display(ar13fl)

array(['a', 'd', 'b', 'e', 'g', 'p'], dtype='<U1')

array(['a', 'e', 'p'], dtype='<U1')

### `shuffle`

In [28]:
display(ar5)
np.random.shuffle(ar5)
display(ar5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([7, 0, 2, 8, 9, 6, 5, 3, 4, 1])

### `unique`

In [29]:
ar14 = np.array([1,5,7,3,2,6,5,2,3,4,1,2,8,3,7,0,4,2])
display('ar14', ar14)
ar14u = np.unique(ar14, return_index=True, return_counts=True)
display(ar14u)

'ar14'

array([1, 5, 7, 3, 2, 6, 5, 2, 3, 4, 1, 2, 8, 3, 7, 0, 4, 2])

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([15,  0,  4,  3,  9,  1,  5,  2, 12], dtype=int64),
 array([1, 2, 4, 3, 2, 2, 1, 2, 1], dtype=int64))

### `resize`, `flatten`, `ravel`
Order for `flatten` (optional): {'C', 'F', 'A', 'K'}
1. 'C' means to flatten in row-major (C-style) order. It's the default.
2. 'F' means to flatten in column-major (Fortran-style) order.
3. 'A' means to flatten in column-major order if 'a' is Fortran contiguous in memory, row-major order otherwise.
4. 'K' means to flatten 'a' in the order the elements occur in memory.

In [30]:
ar14r = np.resize(ar14, (3,6))
display(ar14r)
display(ar14r.flatten(order='F'), 
        np.ravel(ar14r, order='A'))

array([[1, 5, 7, 3, 2, 6],
       [5, 2, 3, 4, 1, 2],
       [8, 3, 7, 0, 4, 2]])

array([1, 5, 8, 5, 2, 3, 7, 3, 7, 3, 4, 0, 2, 1, 4, 6, 2, 2])

array([1, 5, 7, 3, 2, 6, 5, 2, 3, 4, 1, 2, 8, 3, 7, 0, 4, 2])

### `insert`, `append`

In [31]:
display('ar5', ar5)
ar5in = np.insert(ar5, (3,7), 16.3) # dtype not changed (16 taken instead of 16.3)
ar5ap = np.append(ar5, [5.25,6.16,12.43])  # dtype changed automatically
display(ar5in, ar5ap)

'ar5'

array([7, 0, 2, 8, 9, 6, 5, 3, 4, 1])

array([ 7,  0,  2, 16,  8,  9,  6,  5, 16,  3,  4,  1])

array([ 7.  ,  0.  ,  2.  ,  8.  ,  9.  ,  6.  ,  5.  ,  3.  ,  4.  ,
        1.  ,  5.25,  6.16, 12.43])

In [32]:
display('ar2d', ar2d)
ar2din = np.insert(ar2d, 3, [2.15,4], axis=1)
ar2dap = np.append(ar2d, [[1,5,9,2]], axis=0)
display(ar2din, ar2dap)

'ar2d'

array([[1. , 3. , 7. , 8. ],
       [0.2, 3. , 4. , 9. ]])

array([[1.  , 3.  , 7.  , 2.15, 8.  ],
       [0.2 , 3.  , 4.  , 4.  , 9.  ]])

array([[1. , 3. , 7. , 8. ],
       [0.2, 3. , 4. , 9. ],
       [1. , 5. , 9. , 2. ]])

### `delete`

In [33]:
display(ar5ap)
ar5apdl = np.delete(ar5ap, 11) # input index
display(ar5apdl, ar5ap)

array([ 7.  ,  0.  ,  2.  ,  8.  ,  9.  ,  6.  ,  5.  ,  3.  ,  4.  ,
        1.  ,  5.25,  6.16, 12.43])

array([ 7.  ,  0.  ,  2.  ,  8.  ,  9.  ,  6.  ,  5.  ,  3.  ,  4.  ,
        1.  ,  5.25, 12.43])

array([ 7.  ,  0.  ,  2.  ,  8.  ,  9.  ,  6.  ,  5.  ,  3.  ,  4.  ,
        1.  ,  5.25,  6.16, 12.43])

## Numpy - `matrix`

In [34]:
list4 = [[1,2,3],[1,2,3]]
list5 = [[8,6,4],[1,5,6],[7,2,3]]
list6 = [[2,9,6],[7,2,3],[0,8,6]]

ar1m = np.array(list4)
ar2m = np.array(list5)
ar3m = np.array(list6)
display(type(ar1m), ar1m, ar2m, ar3m)

mat1 = np.matrix(list4)
mat2 = np.matrix(list5)
mat3 = np.matrix(list6)
display(type(mat1), mat1, mat2, mat3)

display('5m2-4m3', 5*ar2m-4*ar3m, 5*mat2-4*mat3)
display('m2*m3', ar2m*ar3m, ar2m@ar3m, ar2m.dot(ar3m), mat2*mat3, mat2.dot(mat3))
# here we need to broadcast (maintain the orders) before matrix multiplication

numpy.ndarray

array([[1, 2, 3],
       [1, 2, 3]])

array([[8, 6, 4],
       [1, 5, 6],
       [7, 2, 3]])

array([[2, 9, 6],
       [7, 2, 3],
       [0, 8, 6]])

numpy.matrix

matrix([[1, 2, 3],
        [1, 2, 3]])

matrix([[8, 6, 4],
        [1, 5, 6],
        [7, 2, 3]])

matrix([[2, 9, 6],
        [7, 2, 3],
        [0, 8, 6]])

'5m2-4m3'

array([[ 32,  -6,  -4],
       [-23,  17,  18],
       [ 35, -22,  -9]])

matrix([[ 32,  -6,  -4],
        [-23,  17,  18],
        [ 35, -22,  -9]])

'm2*m3'

array([[16, 54, 24],
       [ 7, 10, 18],
       [ 0, 16, 18]])

array([[ 58, 116,  90],
       [ 37,  67,  57],
       [ 28,  91,  66]])

array([[ 58, 116,  90],
       [ 37,  67,  57],
       [ 28,  91,  66]])

matrix([[ 58, 116,  90],
        [ 37,  67,  57],
        [ 28,  91,  66]])

matrix([[ 58, 116,  90],
        [ 37,  67,  57],
        [ 28,  91,  66]])

### `matrix` functions

In [35]:
display(mat2, 'transpose', np.transpose(mat2), mat2.T)
display('swapaxes', np.swapaxes(mat2,0,1))
display('inverse', np.linalg.inv(mat2))
display('power', np.linalg.matrix_power(mat2,-2))
display('determinant', np.linalg.det(mat2))
display('rank', np.linalg.matrix_rank(mat2))

matrix([[8, 6, 4],
        [1, 5, 6],
        [7, 2, 3]])

'transpose'

matrix([[8, 1, 7],
        [6, 5, 2],
        [4, 6, 3]])

matrix([[8, 1, 7],
        [6, 5, 2],
        [4, 6, 3]])

'swapaxes'

matrix([[8, 1, 7],
        [6, 5, 2],
        [4, 6, 3]])

'inverse'

matrix([[ 0.02380952, -0.07936508,  0.12698413],
        [ 0.30952381, -0.03174603, -0.34920635],
        [-0.26190476,  0.20634921,  0.26984127]])

'power'

matrix([[-0.05725624,  0.02683296,  0.06500378],
        [ 0.08900227, -0.09561602, -0.04383976],
        [-0.01303855,  0.06991686, -0.03250189]])

'determinant'

126.0

'rank'

3