# [Basic Operations on Quantum Objects](https://qutip.org/docs/latest/guide/guide-basics.html)

Link: https://qutip.org/docs/latest/guide/guide-basics.html

In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import sympy as sp
# import plotly.express as px
# import plotly.graph_objects as go

In [1]:
from qutip import *

In [2]:
qutip.about()


QuTiP: Quantum Toolbox in Python
Copyright (c) QuTiP team 2011 and later.
Current admin team: Alexander Pitchford, Nathan Shammah, Shahnawaz Ahmed, Neill Lambert, Eric Giguère, Boxi Li, Jake Lishman, Simon Cross and Asier Galicia.
Board members: Daniel Burgarth, Robert Johansson, Anton F. Kockum, Franco Nori and Will Zeng.
Original developers: R. J. Johansson & P. D. Nation.
Previous lead developers: Chris Granade & A. Grimsmo.
Currently developed through wide collaboration. See https://github.com/qutip for details.

QuTiP Version:      4.7.3
Numpy Version:      1.24.1
Scipy Version:      1.10.1
Cython Version:     None
Matplotlib Version: 3.6.3
Python Version:     3.11.5
Number of CPUs:     12
BLAS Info:          OPENBLAS
OPENMP Installed:   False
INTEL MKL Ext:      False
Platform Info:      Windows (AMD64)
Installation path:  C:\Users\suman\AppData\Roaming\Python\Python311\site-packages\qutip
Please cite QuTiP in your publication.
For your convenience a bibtex reference can be easi

In [3]:
qutip.cite()

@article{qutip2,
doi = {10.1016/j.cpc.2012.11.019},
url = {https://doi.org/10.1016/j.cpc.2012.11.019},
year  = {2013},
month = {apr},
publisher = {Elsevier {BV}},
volume = {184},
number = {4},
pages = {1234--1240},
author = {J.R. Johansson and P.D. Nation and F. Nori},
title = {{QuTiP} 2: A {P}ython framework for the dynamics of open quantum systems},
journal = {Computer Physics Communications}
}
@article{qutip1,
doi = {10.1016/j.cpc.2012.02.021},
url = {https://doi.org/10.1016/j.cpc.2012.02.021},
year  = {2012},
month = {aug},
publisher = {Elsevier {BV}},
volume = {183},
number = {8},
pages = {1760--1772},
author = {J.R. Johansson and P.D. Nation and F. Nori},
title = {{QuTiP}: An open-source {P}ython framework for the dynamics of open quantum systems},
journal = {Computer Physics Communications}
}


## [The Quantum Object class](https://qutip.org/docs/latest/guide/guide-basics.html#the-quantum-object-class)

In [40]:
Qobj() # blank

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]

By convention, the names of Python classes, such as [**`qutip.Qobj()`**](https://qutip.org/docs/latest/apidoc/classes.html#qutip.Qobj), are capitalized whereas the names of functions are not.

In [41]:
Qobj([[1],[2],[4],[6]]) # 4X1 array

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [2.]
 [4.]
 [6.]]

In [42]:
ketvec1 = np.array([5,3,5,7])  # 4X_ array
Qobj(ketvec1)

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[5.]
 [3.]
 [5.]
 [7.]]

In [43]:
bravec1 = np.array([[5,6,7,0]]) # 1X4 array
Qobj(bravec1)

Quantum object: dims = [[1], [4]], shape = (1, 4), type = bra
Qobj data =
[[5. 6. 7. 0.]]

In [44]:
opmat1 = np.random.rand(4,4) # 4X4 array
Qobj(opmat1)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.17941103 0.46584094 0.24535724 0.12282665]
 [0.69824587 0.75605184 0.31434193 0.22673961]
 [0.89346505 0.28888439 0.28438641 0.09664995]
 [0.7810268  0.37288025 0.75894338 0.84221858]]

### [States and Operators](https://qutip.org/docs/latest/guide/guide-basics.html#states-and-operators)

QuTiP includes predefined objects for a variety of states and operators:

| States                                | Command (optional)                               | Inputs                                                   |
| ------------------------------------- | ------------------------------------ | -------------------------------------------------------- |
| Fock state ket vector                  | `basis(N, m)` / `fock(N, m)`                  | N = number of levels in Hilbert space, m = level containing excitation (0 if not given) |
| Fock density matrix (outer product of basis) | `fock_dm(N, p)`                               | same as basis(N, m) / fock(N, m)                       |
| Coherent state                        | `coherent(N, alpha)`                         | alpha = complex number (eigenvalue) for requested coherent state |
| Coherent density matrix (outer product) | `coherent_dm(N, alpha)`                      | same as coherent(N, alpha)                              |
| Thermal density matrix (for n particles) | `thermal_dm(N, n)`                          | n = particle number expectation value                    |


| Operators                             | Command (optional)                         | Inputs                                                          |
| ------------------------------------- | ------------------------------------ | --------------------------------------------------------------- |
| Charge operator                        | `charge(N, M=-N)`                        | Diagonal operator with entries from M..0..N.                   |
| Commutator                            | `commutator(A, B, kind)`                 | Kind = 'normal' or 'anti'.                                     |
| Diagonals operator                    | `qdiags(N)`                              | Quantum object created from arrays of diagonals at given offsets. |
| Displacement operator (Single-mode)    | `displace(N, alpha)`                     | N=number of levels in Hilbert space, alpha = complex displacement amplitude. |
| Higher spin operators                  | `jmat(j, s)`                            | j = integer or half-integer representing spin, s = 'x', 'y', 'z', '+', or '-'. |
| Identity                               | `qeye(N)`                                | N = number of levels in Hilbert space.                         |
| Lowering (destruction) operator       | `destroy(N)`                             | same as above.                                                  |
| Momentum operator                      | `momentum(N)`                            | same as above.                                                  |
| Number operator                        | `num(N)`                                 | same as above.                                                  |
| Phase operator (Single-mode)          | `phase(N, phi0)`                        | Single-mode Pegg-Barnett phase operator with ref phase phi0.   |
| Position operator                      | `position(N)`                            | same as above.                                                  |
| Raising (creation) operator            | `create(N)`                              | same as above.                                                  |
| Squeezing operator (Single-mode)      | `squeeze(N, sp)`                         | N=number of levels in Hilbert space, sp = squeezing parameter.  |
| Squeezing operator (Generalized)      | `squeezing(q1, q2, sp)`                  | q1, q2 = Quantum operators (Qobj), sp = squeezing parameter.    |
| Sigma-X                               | `sigmax()`                               |                                                                |
| Sigma-Y                               | `sigmay()`                               |                                                                |
| Sigma-Z                               | `sigmaz()`                               |                                                                |
| Sigma plus                            | `sigmap()`                               |                                                                |
| Sigma minus                           | `sigmam()`                               |                                                                |
| Tunneling operator                     | `tunneling(N, m)`                        | Tunneling operator with elements of the form `$|N\rangle\langle N+m|+|N+m\rangle\langle N|$`. |

Tunneling operator with elements of the form $|N\rangle\langle N+m|+|N+m\rangle\langle N|$.


In [45]:
basis(5, 3)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]]

In [46]:
coherent(5, 0.5-0.5j)

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[ 0.7788017 +0.j        ]
 [ 0.38939142-0.38939142j]
 [ 0.        -0.27545895j]
 [-0.07898617-0.07898617j]
 [-0.04314271+0.j        ]]

In [47]:
destroy(4)

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

In [48]:
sigmaz()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

In [49]:
jmat(5/2, '+')

Quantum object: dims = [[6], [6]], shape = (6, 6), type = oper, isherm = False
Qobj data =
[[0.         2.23606798 0.         0.         0.         0.        ]
 [0.         0.         2.82842712 0.         0.         0.        ]
 [0.         0.         0.         3.         0.         0.        ]
 [0.         0.         0.         0.         2.82842712 0.        ]
 [0.         0.         0.         0.         0.         2.23606798]
 [0.         0.         0.         0.         0.         0.        ]]

### [**`Qobj`** attributes](https://qutip.org/docs/latest/guide/guide-basics.html#qobj-attributes)

| Property        | Attribute          | Description                                                                                     |
| --------------- | ------------------ | ----------------------------------------------------------------------------------------------- |
| Data            | `Q.data`           | Matrix representing state or operator                                                           |
| Dimensions      | `Q.dims`           | List keeping track of shapes for individual components of a multipartite system (for tensor products and partial traces). |
| Shape           | `Q.shape`          | Dimensions of underlying data matrix.                                                            |
| is Hermitian?   | `Q.isherm`         | Is the operator Hermitian or not?                                                                |
| Type            | `Q.type`           | Is object of type 'ket', 'bra', 'oper', or 'super'?                                             |


In [50]:
q = destroy(4)
print(q.dims)
print(q.shape)
print(q.type)
print(q.isherm)
display(q.data)
print(q.data)

[[4], [4]]
(4, 4)
oper
False


<4x4 sparse matrix of type '<class 'numpy.complex128'>'
	with 3 stored elements in Compressed Sparse Row format>

  (0, 1)	(1+0j)
  (1, 2)	(1.4142135623730951+0j)
  (2, 3)	(1.7320508075688772+0j)


In [51]:
Qobj.full(q)

array([[0.        +0.j, 1.        +0.j, 0.        +0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 1.41421356+0.j, 0.        +0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 1.73205081+0.j],
       [0.        +0.j, 0.        +0.j, 0.        +0.j, 0.        +0.j]])

### [Qobj Math](https://qutip.org/docs/latest/guide/guide-basics.html#qobj-math)

In [52]:
q = destroy(4)
x = sigmax()
display('q', q, 'q+5', q+5, 'q^3', q**3)
display('x', x, 'x*x', x*x, x**2, 'x/rt2', x/np.sqrt(2))

'q'

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         1.         0.         0.        ]
 [0.         0.         1.41421356 0.        ]
 [0.         0.         0.         1.73205081]
 [0.         0.         0.         0.        ]]

'q+5'

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[5.         1.         0.         0.        ]
 [0.         5.         1.41421356 0.        ]
 [0.         0.         5.         1.73205081]
 [0.         0.         0.         5.        ]]

'q^3'

Quantum object: dims = [[4], [4]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[0.         0.         0.         2.44948974]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]

'x'

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

'x*x'

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[1. 0.]
 [0. 1.]]

'x/rt2'

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.         0.70710678]
 [0.70710678 0.        ]]

## [Functions operating on Qobj class](https://qutip.org/docs/latest/guide/guide-basics.html#functions-operating-on-qobj-class)

| Function           | Command                 | Description                                                  |
| ------------------- | ----------------------- | ------------------------------------------------------------ |
| Check Hermicity    | `Q.check_herm()`        | Check if quantum object is Hermitian.                        |
| Conjugate          | `Q.conj()`              | Conjugate of quantum object.                                  |
| Cosine             | `Q.cosm()`              | Cosine of quantum object.                                    |
| Dagger (adjoint)   | `Q.dag()`               | Returns adjoint (dagger) of object.                           |
| Diagonal           | `Q.diag()`              | Returns the diagonal elements.                               |
| Diamond Norm       | `Q.dnorm()`             | Returns the diamond norm.                                    |
| Eigenenergies      | `Q.eigenenergies()`     | Eigenenergies (values) of operator.                          |
| Eigenstates        | `Q.eigenstates()`       | Returns eigenvalues and eigenvectors.                        |
| Eliminate States   | `Q.eliminate_states(inds)` | Returns quantum object with states in the list inds removed. |
| Exponential        | `Q.expm()`              | Matrix exponential of operator.                              |
| Extract States     | `Q.extract_states(inds)` | Qobj with states listed in inds only.                        |
| Full               | `Q.full()`              | Returns a full (not sparse) array of Q's data.               |
| Groundstate        | `Q.groundstate()`       | Eigenval & eigket of Qobj groundstate.                       |
| Matrix Element     | `Q.matrix_element(bra, ket)` | Matrix element <bra|Q|ket>.                                |
| Norm               | `Q.norm()`              | Returns L2 norm for states, trace norm for operators.        |
| Overlap            | `Q.overlap(state)`      | Overlap between the current Qobj and a given state.         |
| Partial Trace      | `Q.ptrace(sel)`         | Partial trace returning components selected using the 'sel' parameter. |
| Permute            | `Q.permute(order)`      | Permutes the tensor structure of a composite object in the given order. |
| Projector          | `Q.proj()`              | Form a projector operator from a given ket or bra vector.    |
| Sine               | `Q.sinm()`              | Sine of a quantum operator.                                  |
| Sqrt               | `Q.sqrtm()`             | Matrix square root of the operator.                         |
| Tidyup             | `Q.tidyup()`            | Removes small elements from the Qobj.                        |
| Trace              | `Q.tr()`                | Returns the trace of the quantum object.                    |
| Transform          | `Q.transform(inpt)`     | A basis transformation defined by a matrix or a list of kets 'inpt'. |
| Transpose          | `Q.trans()`             | Transpose of the quantum object.                             |
| Truncate Neg       | `Q.trunc_neg()`         | Truncates negative eigenvalues.                               |
| Unit               | `Q.unit()`              | Returns the normalized (unit) vector Q/Q.norm().             |


In [53]:
ket1 = basis(5,2)
display('|1>', ket1)
display('daggar = <1|', ket1.dag())

'|1>'

Quantum object: dims = [[5], [1]], shape = (5, 1), type = ket
Qobj data =
[[0.]
 [0.]
 [1.]
 [0.]
 [0.]]

'daggar = <1|'

Quantum object: dims = [[1], [5]], shape = (1, 5), type = bra
Qobj data =
[[0. 0. 1. 0. 0.]]

In [54]:
op1 = coherent_dm(5, 1)
display('op1', op1)
display('diag', op1.diag(), 'full', op1.full())
display('norm', op1.norm())
display('sqrtm', op1.sqrtm())
display('trace', op1.tr(), op1)

'op1'

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

'diag'

array([0.36791117, 0.36757705, 0.18523331, 0.05810197, 0.0211765 ])

'full'

array([[0.36791117+0.j, 0.36774407+0.j, 0.26105441+0.j, 0.14620658+0.j,
        0.08826704+0.j],
       [0.36774407+0.j, 0.36757705+0.j, 0.26093584+0.j, 0.14614018+0.j,
        0.08822695+0.j],
       [0.26105441+0.j, 0.26093584+0.j, 0.18523331+0.j, 0.10374209+0.j,
        0.06263061+0.j],
       [0.14620658+0.j, 0.14614018+0.j, 0.10374209+0.j, 0.05810197+0.j,
        0.035077  +0.j],
       [0.08826704+0.j, 0.08822695+0.j, 0.06263061+0.j, 0.035077  +0.j,
        0.0211765 +0.j]])

'norm'

1.0000000228382986

'sqrtm'

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = False
Qobj data =
[[0.36791119+0.00000000e+00j 0.36774406+0.00000000e+00j
  0.2610544 +0.00000000e+00j 0.14620658+0.00000000e+00j
  0.08826704+0.00000000e+00j]
 [0.36774406+0.00000000e+00j 0.36757705+4.23874181e-11j
  0.26093584+1.25558676e-10j 0.14614018-2.58178591e-10j
  0.08822695-1.20293587e-10j]
 [0.2610544 +0.00000000e+00j 0.26093584+1.25558676e-10j
  0.18523332+3.71925960e-10j 0.10374209-7.64768498e-10j
  0.06263061-3.56329879e-10j]
 [0.14620658+0.00000000e+00j 0.14614018-2.58178591e-10j
  0.10374209-7.64768498e-10j 0.05810197+1.57254647e-09j
  0.035077  +7.32699235e-10j]
 [0.08826704+0.00000000e+00j 0.08822695-1.20293587e-10j
  0.06263061-3.56329879e-10j 0.035077  +7.32699235e-10j
  0.0211765 +3.41387792e-10j]]

'trace'

1.0

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.36791117 0.36774407 0.26105441 0.14620658 0.08826704]
 [0.36774407 0.36757705 0.26093584 0.14614018 0.08822695]
 [0.26105441 0.26093584 0.18523331 0.10374209 0.06263061]
 [0.14620658 0.14614018 0.10374209 0.05810197 0.035077  ]
 [0.08826704 0.08822695 0.06263061 0.035077   0.0211765 ]]

In [55]:
add12 = basis(4,1) + basis(4,2)
display('addition', add12, 'unit', add12.unit())

'addition'

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [1.]
 [0.]]

'unit'

Quantum object: dims = [[4], [1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]